/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ntluong94
 */
public class Ceasar extends javax.swing.JFrame {


    public Ceasar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPlain = new javax.swing.JLabel();
        lblKey = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea_Plain = new javax.swing.JTextArea();
        txtKey = new javax.swing.JTextField();
        btnEncrypt = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        lblCipher = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtArea_Cipher = new javax.swing.JTextArea();
        btn_Decrypt = new javax.swing.JButton();
        btb_mo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chương trình mã hóa/ giải mã Ceasar Cipher");

        lblPlain.setText("Plaintext:");

        lblKey.setText("Khóa:");

        TxtArea_Plain.setColumns(20);
        TxtArea_Plain.setRows(5);
        jScrollPane1.setViewportView(TxtArea_Plain);

        btnEncrypt.setText("v Encrypt v");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnGhi.setText("Ghi File");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        lblCipher.setText("Cipher text: ");

        TxtArea_Cipher.setColumns(20);
        TxtArea_Cipher.setRows(5);
        jScrollPane3.setViewportView(TxtArea_Cipher);

        btn_Decrypt.setText("^ Decrypt ^");
        btn_Decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DecryptActionPerformed(evt);
            }
        });

        btb_mo.setText("Mở File");
        btb_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_moActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlain)
                            .addComponent(lblKey)
                            .addComponent(lblCipher))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEncrypt)
                                    .addGap(60, 60, 60)
                                    .addComponent(btnGhi))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Decrypt)
                                .addGap(64, 64, 64)
                                .addComponent(btb_mo)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlain)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKey)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnGhi))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCipher))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Decrypt)
                    .addComponent(btb_mo))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        String plaintext = TxtArea_Plain.getText();
        String key = txtKey.getText();
        int khoa ;
        if(key.equals(" ") || plaintext.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin!");
        }
        khoa = Integer.parseInt(key);
        if(khoa <0)
        {
            khoa = 26 - (-khoa % 26);   
        }
        String rs ="";
        for(int i =0; i< plaintext.length(); i++)
        {
            char c = mahoa(plaintext.charAt(i),khoa);
            rs = rs + c;
        }
        TxtArea_Cipher.setText(rs);   
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        try{
            BufferedWriter bw = null;
            String url ="C:\\file.txt";
            String text = TxtArea_Cipher.getText();
            bw = new BufferedWriter(new FileWriter(url));
            
           bw.write(text);
           bw.close();
            JOptionPane.showMessageDialog(null, "Ghi file thành công");
        }
        catch (IOException e)
        {
            //Logger.getLogger(Ceasar.class.getName()).log(Level.SEVERE, null,e);
        }
        
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btn_DecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DecryptActionPerformed
        String ciphertext = TxtArea_Cipher.getText();
        String key = txtKey.getText();
       
        int khoa = Integer.parseInt(key);
        if(ciphertext.equals("")|| key.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin!");
        }
        if(khoa <0)
        {
            khoa = 26 - (-khoa % 26);
        }
        String rs ="";
        for(int i =0; i< ciphertext.length(); i++)
        {
            char c = giaima(ciphertext.charAt(i),khoa);
            rs = rs + c;
        }
        TxtArea_Plain.setText(rs);
        
    }//GEN-LAST:event_btn_DecryptActionPerformed

    private void btb_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_moActionPerformed
       try
       {
           BufferedReader br = null;
           String url ="C:\\file.txt";
           br = new BufferedReader(new FileReader(url));
           StringBuffer sb = new StringBuffer();
           JOptionPane.showMessageDialog(null, "Mở file thành công");
           char[] a = new char[5];
           while(br.ready())
           {
               int len = br.read(a);
               sb.append(a, 0, len);
            }
           br.close();
           System.out.println("text : " + " " + sb);
           String string = sb.toString();
           TxtArea_Cipher.setText(string);  
       }
       catch (IOException e)
          {
              //Logger.getLogger(Ceasar.class.getName()).log(Level.SEVERE, null,e);
          }
        
    }//GEN-LAST:event_btb_moActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ceasar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtArea_Cipher;
    private javax.swing.JTextArea TxtArea_Plain;
    private javax.swing.JButton btb_mo;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btn_Decrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCipher;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblPlain;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables

    private char mahoa(char c, int khoa) 
    {
        if (Character.isLetter(c))
        {
            c= (char)('A' + (Character.toUpperCase(c)-'A' +khoa)% 26);
        }
        return c;
    }

    private char giaima(char c, int khoa) {
        if (Character.isLetter(c))
        {
            c= (char)('A' + (Character.toUpperCase(c)-'A' - khoa)% 26);
        }
        return c;
    }
    
}
//Tăng đơ vị trong bảng chử cái