/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab1;

import javax.swing.JOptionPane;

public class Rail_Fence extends javax.swing.JFrame {

    /**
     * Creates new form Rail_Fence
     */
    public Rail_Fence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea_Plain = new javax.swing.JTextArea();
        txt_Key = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Encypt = new javax.swing.JButton();
        btn_Dencypt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtArea_Cipher = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Thuật toán mã hóa/ giải mã  Rail Fence");

        jLabel2.setText("Plaintext: ");

        jLabel3.setText("Key: ");

        TxtArea_Plain.setColumns(20);
        TxtArea_Plain.setRows(5);
        jScrollPane1.setViewportView(TxtArea_Plain);

        jLabel4.setText("CipherText:");

        btn_Encypt.setText("v Encypt v");
        btn_Encypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EncyptActionPerformed(evt);
            }
        });

        btn_Dencypt.setText("^ Dencypt ^");
        btn_Dencypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DencyptActionPerformed(evt);
            }
        });

        TxtArea_Cipher.setColumns(20);
        TxtArea_Cipher.setRows(5);
        jScrollPane2.setViewportView(TxtArea_Cipher);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Encypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Dencypt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Key, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Dencypt)
                    .addComponent(btn_Encypt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EncyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EncyptActionPerformed
        String plaintext = TxtArea_Plain.getText();
        int i =0, c= 0, t=0, j,l,r,s;
        String ciphertext = "";
        String key = txt_Key.getText();
        r = Integer.parseInt(key);
        l = plaintext.length()/r;
        s = 2*l;
        char ct[][]= new char[r][s];
        while(i<r)
        {
            ct[i][c]=plaintext.charAt(t);
            t++;
            if(i==r-1 && t <= plaintext.length()-1)
            {
                c =c +1;
                for(j=r-2;j>=0;j--)
                {
                    ct[j][c]=plaintext.charAt(t);
                    t++;
                    if(j==0 && t<=plaintext.length()-1)
                    {
                        c++;
                        i=0;
                    }
                }
            }
            i= i+1;
           
        }
        for(i=0;i<r;i++)
        {
            for(j=0;j<ct[i].length; j++)
            {
                char d = ct[i][j];
                if(d=='\0')
                {
                    continue;
                }
                else
                {
                    ciphertext = ciphertext + ct[i][j];
                }
            }
        }
        System.out.println("Văn bản sau khi mã hóa: \n" +ciphertext );
        TxtArea_Cipher.setText(ciphertext.toString().toString());
    }//GEN-LAST:event_btn_EncyptActionPerformed

    private void btn_DencyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DencyptActionPerformed
     if(TxtArea_Plain.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nhập PlainText!");
        }
        else if(txt_Key.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Nhập khóa!");
        }
        String plainText = TxtArea_Plain.getText();
        String  cipherText="";
        System.out.printf("Enter the RailS");
        int khoa = Integer.parseInt(txt_Key.getText()); //ep kieu
        int s = (plainText.length()/2);
        int k=0;
        char ct[][] = new char[khoa][s];
        for(int i=0;i<khoa;i++){
            for(int j=0;j<s;j++){
                if(k>=plainText.length()){//k =  độ dài plain text 
                    break;
                }
                ct[i][j] = plainText.charAt(k);
                k++;
                System.out.println(ct[i][j]+" ");
            }
            System.out.println(" ");
        }
        for(int i=0;i<s;i++){
            for(int j=0;j<khoa;j++){
                if(ct[j][i]==0){
                    cipherText+='\0';
                }
                else{
                    cipherText+=ct[j][i];
                }
            }
        }
        String s1="";
        for(k=0;k<cipherText.length();k++){
            if((int)cipherText.charAt(k)!=0){
                s1+=cipherText.charAt(k);
            }
        }
        TxtArea_Cipher.setText(s1);
    }//GEN-LAST:event_btn_DencyptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rail_Fence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rail_Fence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rail_Fence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rail_Fence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rail_Fence().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtArea_Cipher;
    private javax.swing.JTextArea TxtArea_Plain;
    private javax.swing.JButton btn_Dencypt;
    private javax.swing.JButton btn_Encypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_Key;
    // End of variables declaration//GEN-END:variables
}
//chuyển vị  HUTECH TECHNOLOGY
// HTCTCNLG
// UEHEHOOY

