/*
 * SHA_login.java
 *
 * Created on July 27, 2013, 7:27 PM
 */

package Lab5;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.StringReader;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
/**
 * @author ntluong
 */
public class SHA_login extends javax.swing.JFrame {
    
    /** Creates new form SHA_login */
    public SHA_login() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        txt_Pass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_KQ = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Chuoi = new javax.swing.JTextArea();
        btn_DangKy = new javax.swing.JButton();
        btn_DangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SHA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Username :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Result :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Chuỗi :");

        txt_KQ.setColumns(20);
        txt_KQ.setRows(5);
        jScrollPane1.setViewportView(txt_KQ);

        txt_Chuoi.setColumns(20);
        txt_Chuoi.setRows(5);
        jScrollPane2.setViewportView(txt_Chuoi);

        btn_DangKy.setText("Đăng ký");
        btn_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangKyActionPerformed(evt);
            }
        });

        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25)
                                .addComponent(btn_DangKy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_DangNhap))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txt_Pass)
                                    .addComponent(txt_User))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangKy)
                    .addComponent(btn_DangNhap))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangKyActionPerformed
       try
       {
           String user = txt_User.getText();
           String pass = txt_Pass.getText();
           String bam = "";
           bam = user + pass;
           MessageDigest md = MessageDigest.getInstance("SHA-256");
           md.update(bam.getBytes());
           byte [] data = md.digest();
           StringBuffer sb = new StringBuffer();
            for (int i = 0; i<data.length; i++)
            {
                sb.append(Integer.toString((data[i] & 0xff) + 0x100, 16 ).substring(1));
            }
            System.out.println("hex 1 :" + sb.toString());
            txt_KQ.setText(sb.toString());
            txt_Chuoi.setText(bam.toString());
           BufferedWriter bw =null;
           String file = "D:\\HashLogin.txt";
           bw = new BufferedWriter(new FileWriter(file));
           bw.write(sb.toString());
           bw.close();
          
            JOptionPane.showMessageDialog(null, "Dang ky thanh cong!");           
       }
       catch(Exception e)
       {
           System.out.println("loi: " + e);
       }
    }//GEN-LAST:event_btn_DangKyActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        String user =txt_User.getText();
        String pass = txt_Pass.getText();
        String bam = user + pass;
        BufferedReader br;
        String file ="D:\\HashLogin.txt";
        try
        {
           br = new BufferedReader(new FileReader(file));
           StringBuffer sb = new StringBuffer();
            char [] c = new char[5];
                while(br.ready())
                {
                   int l = br.read(c);
                   sb.append(c,0,l);
                }
                br.close(); 
                System.out.println("chuoi: "+sb.toString());
                String chuoi = sb.toString();
                MessageDigest md = MessageDigest.getInstance("SHA-256");
                md.update(bam.getBytes());
                byte []data = md.digest();
                StringBuffer hexstring = new StringBuffer();
                for (int i = 0; i<data.length; i++)
                {
                    String hex = Integer.toHexString(0xff & data[i]);
                    if(hex.length()==1)
                    {
                        hexstring.append('0');
                    }
                    hexstring.append(hex);
                }System.out.println("chuoi:"+ " " +hexstring.toString());
              Boolean k = hexstring.toString().equals(chuoi);
              if(k==true)
              {
                  JOptionPane.showMessageDialog(null, "Dang nhap thanh cong!");
                  txt_KQ.setText(hexstring.toString());
                  txt_Chuoi.setText("User: " + user + " " +"Pass : "+pass);
              }
              else
              {
                  JOptionPane.showMessageDialog(null, "Dang nhap that bai! :(");           
                }
        }
        catch(Exception e)
        {
            System.out.println("loi" + e);
        }
    }//GEN-LAST:event_btn_DangNhapActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHA_login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangKy;
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_Chuoi;
    private javax.swing.JTextArea txt_KQ;
    private javax.swing.JTextField txt_Pass;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
    
}
